#! /bin/bash
#
# debian/repack
# Part of the Debian package ‘roundcube’.
#
# Copyright © 2013–2014 Ben Finney <ben+debian@benfinney.id.au>
# This is free software; you may copy, modify and/or distribute this work
# under the terms of the GNU General Public License, version 3 or later.
# No warranty expressed or implied. See the file ‘LICENSE’ for details.

# Convert the pristine upstream source to the Debian upstream source.
#
# This program is designed for use with the ‘uscan(1)’ tool, as the
# “action” parameter for the ‘debian/watch’ configuration file.

set -o errexit
set -o errtrace
set -o pipefail
set -o nounset

program_dir="$(dirname "$(realpath --strip "$0")")"
source "${program_dir}"/source_package_build.bash

function usage() {
    local progname=$(basename $0)
    printf "$progname --upstream-version VERSION FILENAME\n"
}

if [ $# -ne 3 ] ; then
    usage
    exit 1
fi

upstream_version="$2"
downloaded_file="$3"

target_filename="${upstream_tarball_basename}.tar.gz"
target_working_file="${working_dir}/${target_filename}"
target_file="$(dirname "${downloaded_file}")/${target_filename}"

repack_dir="${working_dir}/${upstream_dirname}"

printf "Unpacking pristine upstream source ‘${downloaded_file}’:\n"

extract_tarball_to_working_dir "${downloaded_file}"

upstream_source_dirname=$(ls -1 "${working_dir}")
upstream_source_dir="${working_dir}/${upstream_source_dirname}"

printf "Repackaging upstream source from ‘${upstream_source_dir}’ to ‘${repack_dir}’:\n"

mv "${upstream_source_dir}" "${repack_dir}"

printf "Removing non-source files:\n"

source_omit_files=(
        # Third-party libraries in non-source form, and related files.
        plugins/acl/*.min.js
        plugins/archive/*.min.js
        plugins/attachment_reminder/*.min.js
        plugins/enigma/*.min.js
        plugins/help/*.min.js
        plugins/hide_blockquote/*.min.js
        plugins/jqueryui/
        plugins/managesieve/*.min.js
        plugins/markasjunk/*.min.js
        plugins/newmail_notifier/*.min.js
        plugins/password/*.min.js
        plugins/userinfo/*.min.js
        plugins/vcard_attachments/*.min.js
        plugins/zipdownload/*.min.js
        program/js/*.min.js
        program/js/tiny_mce/
        )

for fileglob in "${source_omit_files[@]}" ; do
    rm -v -r "${repack_dir}"/$fileglob
done

printf "Rebuilding DFSG-free upstream source tarball:\n"

archive_working_dirname_to_tarball "${upstream_dirname}" "${target_working_file}"

printf "Moving completed upstream tarball to ‘${target_file}’:\n"

rm -v "${downloaded_file}"
mv "${target_working_file}" "${target_file}"

printf "Done.\n"


# Local variables:
# coding: utf-8
# mode: sh
# indent-tabs-mode: nil
# End:
# vim: fileencoding=utf-8 filetype=bash :
